#Authorization related properties
europeana.apikey.serviceurl=
keycloak.token.endpoint=
keycloak.token.grant.params=
keycloak.jwttoken.siganturekey=
api.name.authorization=dataset-api

#Dataset file Storage path ending with forward slash. e.g. /opt/app/storage/
dataset.storage.path.local=
