spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

### DB pool settings
## make sure to have DB maximum-pool-size <= settings.getBatchUpdatesCorePoolSize()
#timeout values are in ms
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
#The maximum lifetime of a connection in the pool before Hikari retires it and replaces it.
#by default Hirakari pool uses 30 minutes =1800 seconds
#spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000


#Force schema initialization explicitly
spring.sql.init.mode=always
spring.batch.jdbc.initialize-schema=always
#this ensures spring loads org/springframework/batch/core/schema-h2.sql
spring.batch.jdbc.platform=h2

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

#to check start up logs
#must see - Executing SQL script from class path resource [org/springframework/batch/core/schema-h2.sql]
#logging.level.org.springframework.batch=DEBUG
#logging.level.org.springframework.jdbc.datasource.init=DEBUG


#logging.level.org.springframework.jdbc.core=DEBUG
#logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

logging:
level:
com.zaxxer.hikari: DEBUG

#INitialisaztion order
#1. DataSource created
#2. schema.sql executed
#3. JPA tables created
#4. Spring Batch schema created
#5. Application runs