<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>eu.europeana.api</groupId>
        <artifactId>dataset-api</artifactId>
        <version>0.1-SNAPSHOT</version>
    </parent>

    <artifactId>dataset-oaipmh</artifactId>
    <name>Dataset OAI PMH Client</name>
    <description>Europeana Dataset API OAI PMH module</description>
    <version>0.1-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>


    <dependencies>

        <dependency>
            <groupId>eu.europeana.api</groupId>
            <artifactId>commons-sb3-clientutils</artifactId>
            <version>${api-commons-sb3.version}</version>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/org.json/json -->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20251224</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.24.3</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>


</project>